blog/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
	url(r'^$', "blog.views.home", name='blog'),
	url(r'^cont/$', "blog.views.cont", name='cont'),
   	url(r'^curric/$', "blog.views.curric", name='curric'),
    	url(r'^eje/$', "blog.views.eje", name='eje'),
	url(r'^eje/calcu/$', "blog.views.calcu", name='calcu'),
	url(r'^eje/conver/$', "blog.views.conver", name='conver'),
	url(r'^eje/crono/$', "blog.views.crono", name='crono'),
	url(r'^eje/boton/$', "blog.views.boton", name='boton'),
	url(r'^eje/loading/$', "blog.views.loading", name='loading'),
	url(r'^ver_post/(?P<id_post>[0-9]+)/$', 'blog.views.ver_post', name='vermipost'),
	url(r'^contacto/$', 'blog.views.contact', name='contacto'),
        url(r'^mensaje/$', 'blog.views.save_message', name='mensaje'),
)

vilca/urls.py
from django.conf.urls import patterns,include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('blog.urls', namespace = "blog_app")),
    url(r'^admin/', include(admin.site.urls)),
]

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

class Entrada(models.Model):
    class Meta:
        verbose_name = "Mi Entrada"
        verbose_name_plural = "Mis entradas"
        ordering=['-fecha']
    
    titulo = models.CharField(u'Título', max_length=100)
    fecha = models.DateTimeField(u'Fecha del Post',auto_now_add=True)
    resumen= models.CharField(u'Resumen',max_length=512)
    contenido = models.TextField(u'Contenido')
    published = models.BooleanField(u'Publicado?', default=True)
    autor = models.ForeignKey(User)
    categoria = models.ManyToManyField('Categoria')

    def __str__(self):
	return self.titulo

class Categoria(models.Model):
    nombre = models.CharField(u'Título de la Categoría', max_length=100)
    descripcion = models.CharField(u'Descripción de la Categoría', max_length=256)
    
    def __str__(self):
        return self.nombre

class Contacto(models.Model):
    class Meta:
        verbose_name = "Contacto"
        verbose_name_plural = "Contactos"
        ordering=['-fecha']

    nombre = models.CharField(u'Nombre', max_length=100)
    mail = models.CharField(u'Mail', max_length=100)
    mensaje = models.TextField(u'Mensaje')
    fecha = models.DateTimeField(u'Fecha del Post',auto_now_add=True)

    def __unicode__(self):
        return self.nombre



class Comentario(models.Model):
    autor = models.CharField(u'Nombre', max_length=100)
    mensaje = models.TextField(u'Mensaje')
    mail = models.TextField(u'Mail', False)
    post = models.ForeignKey(Entrada)
    def __str__(self):
        return self.autor

blog/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response, render, redirect
from blog.models import Entrada, Contacto, Comentario
from django.core.mail import send_mail
from django.conf import settings


# Create your views here.

def home(request):
	context = RequestContext(request)
	posts = Entrada.objects.all()
	post = Entrada.objects.filter(published = True)
   	return render_to_response('Sitio.html', {'posts':post}, context)

def cont(request):
	context = RequestContext(request)
	return render_to_response('Contacto.html',context)

def curric(request):
	context = RequestContext(request)
	return render_to_response('Curriculum.html',context)

def eje(request):
	context = RequestContext(request)
	return render_to_response('Ejercicios.html',context)

def calcu(request):
	context = RequestContext(request)
	return render_to_response('Calculadora.html',context)

def conver(request):
	context = RequestContext(request)
	return render_to_response('Conversor.html',context)

def crono(request):
	context = RequestContext(request)
	return render_to_response('Cronometro.html',context)

def boton(request):
	context = RequestContext(request)
	return render_to_response('Boton.html',context)

def loading(request):
	context = RequestContext(request)
	return render_to_response('BarraCarga.html',context)

def calcu(request):
	context = RequestContext(request)
	return render_to_response('Calculadora.html',context)

def ver_post(request, id_post):
    context = RequestContext(request)
    post = Entrada.objects.get(id=id_post)
    comentarios = Comentario.objects.filter(post_id = id_post)
    return render_to_response('post.html', {'post':post, 'mensajes':comentarios},context)

def contact(request):
    context = RequestContext(request)
    if request.method == 'POST':
        nombre= request.POST['nombre']
        mensaje= request.POST.get('mensaje')
        mail= request.POST['mail']
        contacto = Contacto()
        contacto.nombre = nombre
        contacto.mensaje = mensaje
        contacto.mail = mail
        contacto.save()
        
        send_mail(nombre, mensaje, settings.EMAIL_HOST_USER,['dalmirogrol@gmail.com'], fail_silently=False)
        
    return render_to_response('Contacto.html',
                              context)

def save_message(request):
    context = RequestContext(request)

    if request.method == 'POST':
        mi_post = Entrada.objects.get(id=request.POST['id'])
        nombre= request.POST.get('autor')
        msn= request.POST.get('mensaje')
        mail= request.POST.get('mail')      
        postid = request.POST.get('id') 
        mensaje = Comentario()
        mensaje.autor = nombre
        mensaje.mail = mail
        mensaje.mensaje = msn
        mensaje.post = mi_post
        mensaje.save()
    postid = request.POST.get('id')
    mensajes = Comentario.objects.filter(post=postid)

    return render_to_response('comentarios.html', 
                              {'mensajes':mensajes},
                              context)

        
def ver_mensajes(request, id_mensaje):
    context = RequestContext(request)
    mensajes = Entrada.objects.filter(published = True)
    return render_to_response('post.html', 
                              {'mensaje':mensajes},
                              context)

blog/templates/BarraCarga.html
<html>
    {% load staticfiles %}
    <head>
        <title>Barra de Carga</title>
        <link rel="stylesheet" href="{% static 'css/style2.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    </head>

    <body>
        <script type="text/javascript" src="{% static 'js/jquery-2.1.4.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <div><h1 align="center"><b>Barra de Carga</b></h1></div>


        <div>
            <a class='dropdown-button btn' data-activates='dropdown1' style="width:115px;color:black;">Ir a</a>
            <ul id='dropdown1' class='dropdown-content'>
                <li><a href="{% url 'blog_app:blog' %}">MainSite</a></li>
                <li><a href="{% url 'blog_app:cont' %}">Contacto</a></li>
                <li><a href="{% url 'blog_app:curric' %}">Curriculum</a></li>
                <li><a href="{% url 'blog_app:eje' %}">Ejercicios</a></li>
            </ul>
        </div>


        <div align="center"><progress value=0 max=100 id="barra" class="barraStyle"></progress></div>
        <div align="center"><input type="button" value="Cargar" id="load" onclick="setInterval('load()',190)"/></div>
        <div align="center"><input type="button" value="Stop" id="stop" onclick="stop()" style="width:61.10px;"/></div>


        <script type="text/javascript">
            function load(){
                var aux=0;
                if(aux==0){
                    var barra = document.getElementById("barra");
                    barra.value +=13;
                    var a=barra.value;
                    if(a==100){
                        alert("Carga Finalizada");
                        barra.value=0;
                    }
                }
            }


            function stop(){
                document.location.reload();
            }

        </script>
    </body>
</html>

blog/templates/Boton.html
<html>
    {% load staticfiles %}
    <head>
        <title>Boton</title>
        <link rel="stylesheet" href="{% static 'css/style2.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    </head>

    <body>
        <script type="text/javascript" src="{% static 'js/jquery-2.1.4.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <div><h1 align="center"><b>Boton</b><h1></div>
            <div><h4 align="center"><b>Apriete el Boton...</b></h4></div>


            <div>
                <a class='dropdown-button btn' data-activates='dropdown1' style="width:115px;color:black;">Ir a</a>
                <ul id='dropdown1' class='dropdown-content'>
                    <li><a href="{% url 'blog_app:blog' %}">MainSite</a></li>
                    <li><a href="{% url 'blog_app:cont' %}">Contacto</a></li>
                    <li><a href="{% url 'blog_app:curric' %}">Curriculum</a></li>
                    <li><a href="{% url 'blog_app:eje' %}">Ejercicios</a></li>
                </ul>
            </div>



            <a id="btn" onmouseover="moverboton(this)" onclick="cartel(this)"><img src="{% static 'css/img/boton.png' %}" width=150 height=150 style="margin-left:200px;"></a>

            <script>
                aux = 0;
                boton = document.getElementById("btn");
                aprieta = documet.getElementById("btn").value;

                function moverboton(){
                    if(aux==0){
                        document.getElementById("btn").style.margin="0px 700px";
                        aux=1;
                    }
                    else{ 
                        if(aux==1){
                            document.getElementById("btn").style.margin="0px 0px";
                            aux=2;
                        }
                    }
                    if(aux==2){
                        aux=0;
                    }
                }
            </script>

            <script>
                function cartel(){
                    alert("NO SE PUEDE USAR EL TECLADO!!!!");
                }
            </script>
            </body>
            </html>

blog/templates/Calculadora.html
<html>
    {% load staticfiles %}
    <head>
        <title>Calculadora</title>
        <link rel="stylesheet" href="{% static 'css/style2.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    </head>

    <body>
        <script type="text/javascript" src="{% static 'js/jquery-2.1.4.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <div><h1 align=center><b>Calculadora</b><h1></div>

            <div>
                <a class='dropdown-button btn' data-activates='dropdown1' style="width:115px;color:black;">Ir a</a>
                <ul id='dropdown1' class='dropdown-content'>
                    <li><a href="{% url 'blog_app:blog' %}">MainSite</a></li>
                    <li><a href="{% url 'blog_app:cont' %}">Contacto</a></li>
                    <li><a href="{% url 'blog_app:curric' %}">Curriculum</a></li>
                    <li><a href="{% url 'blog_app:eje' %}">Ejercicios</a></li>
                </ul>
            </div>

            <form class="contacto">
                <input id="resultado" type="text" value="" style="width:300px;"/>

                <br>
                <input type="button" id="btn1" onclick="ejecutar(this)" value="1" style="width:65px;height:85px;" />
                <input type="button" id="btn2" onclick="ejecutar(this)" value="2" style="width:65px;height:85px;"/>
                <input type="button" id="btn3" onclick="ejecutar(this)" value="3" style="width:65px;height:85px;"/>
                <input type="button" id="btnmas" onclick="ejecutar(this)" value="+" style="width:65px;height:85px;"/>
                <br>
                <input type="button" id="btn4" onclick="ejecutar(this)" value="4" style="width:65px;height:85px;"/>
                <input type="button" id="btn5" onclick="ejecutar(this)" value="5" style="width:65px;height:85px;"/>
                <input type="button" id="btn6" onclick="ejecutar(this)" value="6" style="width:65px;height:85px;"/>
                <input type="button" id="btnmenos" onclick="ejecutar(this)" value="-" style="width:65px;height:85px;"/>
                <br>
                <input type="button" id="btn7" onclick="ejecutar(this)" value="7" style="width:65px;height:85px;"/>
                <input type="button" id="btn8" onclick="ejecutar(this)" value="8" style="width:65px;height:85px;"/>
                <input type="button" id="btn9" onclick="ejecutar(this)" value="9" style="width:65px;height:85px;"/>
                <input type="button" id="btnpor" onclick="ejecutar(this)" value="*" style="width:65px;height:85px;"/>
                <br>
                <input type="button" id="btnpunto" onclick="ejecutar(this)" value="." style="width:65px;height:85px;"/>
                <input type="button" id="btn0" onclick="ejecutar(this)" value="0" style="width:65px;height:85px;"/>
                <input type="button" id="btnigual" onclick="ejecutar(this)" value="=" style="width:65px;height:85px;"/>
                <input type="button" id="btndividido" onclick="ejecutar(this)" value="/" style="width:65px;height:85px;"/>
            </form>

            <script>
                newval = 0;

                function ejecutar(botoncitoqueaprete) {
                    if(newval == 0 ){
                        aprieta = botoncitoqueaprete.value;
                        val = document.getElementById("resultado").value;    
                        if (aprieta=="="){
                            newval=1
                            if (val.length!=0){
                                result = eval(val);
                                document.getElementById("resultado").setAttribute("value",result);
                            }
                        }else{
                            document.getElementById("resultado").setAttribute("value",val+aprieta);}
                    }else{
                        aprieta = botoncitoqueaprete.value;
                        if(aprieta!="=" & aprieta!="+" & aprieta!="-" & aprieta!="/" & aprieta!="*"){
                            document.getElementById("resultado").setAttribute("value",aprieta);
                            newval = 0;
                        }
                    }
                }

            </script>   



            <br>

            </body>
            </html>

blog/templates/Contacto.html
{% block content %}
<html>
    {% load staticfiles %}
    <head>
        <title>Contacto</title>
        <link rel="stylesheet" href="{% static 'css/style2.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    </head>

    <body>
        <script type="text/javascript" src="{% static 'js/jquery-2.1.4.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>

        <div style="color:black;"><h2>Contacto</h2></div>

        <a class='dropdown-button btn' data-activates='dropdown1' style="width:115;color:black;">Ir a</a>
        <ul id='dropdown1' class='dropdown-content'>
            <li><a href="{% url 'blog_app:blog' %}">MainSite</a></li>
            <li><a href="{% url 'blog_app:curric' %}">Curriculum</a></li>
            <li><a href="{% url 'blog_app:eje' %}">Ejercicios</a></li>
        </ul>

        <form action="{% url 'blog_app:contacto' %}" method="POST" name="sentMessage" id="contactForm">
            {% csrf_token %}
            <div class="container">
                <ul class="collection with-header">
                    <li class="collection-header"><h4>Info. Principal</h4></li>
                    {{enviado}}
                    <li class="collection-item"><div><b>Nombre y Apellido:</b> Dalmiro Boscossio<a href="#!" class="secondary-content"></a></div></li>
                    <li class="collection-item"><div><b>Telefono / WhatsApp:</b> 0351-12345678<a href="#!" class="secondary-content"></a></div></li>
                    <li class="collection-item"><div><b>O Contactenos Via:</b><a href="www.twitter.com"> Twitter</a><a href="www.facebook.com"> Facebook</a><a href="#!" class="secondary-content"></a></div></li>
                    <li class="collection-item"><div><b>Nombre:</b>
                        <div class="row">
                            <div class="input-field col s6">
                                <input name="nombre"id="first_name2" type="text" style="height:13px;" class="validate">
                            </div>
                        </div>
                    <li class="collection-item"><div><b>Mail:</b>
                        <div class="row">
                            <div class="input-field col s6">
                                <input name="mail"id="first_name2" type="text" style="height:13px;" class="validate">
                            </div>
                        </div>
                        <li class="collection-item"><div><b>Deja tu consulta:</b> 
                            <div class="row">
                                <div class="input-field col s6">
                                    <input id="first_name2" name="mensaje" type="text" style="height:13px;" class="validate">
                                    <input id="first_name2" type="submit" style="color:black;">
                                    </form>
                            </div>
                            </div>
                        </ul>
                    </div>
                </body>
            </html>
        {% endblock %}

blog/templates/Ejercicios.html
<html>
    {% load staticfiles %}
    <head>
        <title>Ejercicios</title>
        <link rel="stylesheet" href="{% static 'css/style2.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    </head>

    <body>
        <script type="text/javascript" src="{% static 'js/jquery-2.1.4.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <div style="color:black;"><h2><b>Ejercicios</b></h2></div>

        <a class='dropdown-button btn' data-activates='dropdown1' style="width:115px;color:black;">Ir a</a>
        <ul id='dropdown1' class='dropdown-content'>
            <li><a href="{% url 'blog_app:blog' %}">MainSite</a></li>
            <li><a href="{% url 'blog_app:cont' %}">Contacto</a></li>
            <li><a href="{% url 'blog_app:curric' %}">Curriculum</a></li>
        </ul>



        <div class="row" style="width:500px;margin-left:3%;margin-top:0px;">
            <div class="col s12 m7">
                <div class="card" style="width:300px;">
                    <div class="card-image">
                        <img src="{% static 'css/img/calculadora.png' %}">
                    </div>
                    <div class="card-content">
                        <p>Este es el primer ejercicio, una calculadora en Javascript.</p>
                    </div>
                    <div class="card-action">
                        <a href="{% url 'blog_app:calcu' %}" style="color:black;"><b>Ir a calculadora</b></a>
                    </div>
                </div>
            </div>
        </div>


        <div class="row" style="width:500px;margin-left:37%;margin-top:-500px;">
            <div class="col s12 m7 l6">
                <div class="card" style="width:300px;height:440px">
                    <div class="card-image">
                        <img src="{% static 'css/img/moneda.png' %}" style="width:270px;margin-left:17px;">
                    </div>
                    <div class="card-content">
                        <p>Este es el segundo ejercicio, un conversor de monedas en Javascript.</p>
                    </div>
                    <div class="card-action">
                        <a href="{% url 'blog_app:conver' %}" style="color:black;"><b>Ir a conversor</b></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row" style="width:644px;margin-left:72%;margin-top:-800px;">
            <div class="col s12 m7 l6">
                <div class="card">
                    <div class="card-image">
                        <img src="{% static 'css/img/cronometro.png' %}">
                    </div>
                    <div class="card-content">
                        <p>Este es el tercer ejercicio, un cronometro en Javascript.</p>
                    </div>
                    <div class="card-action">
                        <a href="{% url 'blog_app:crono' %}" style="color:black;"><b>Ir a cronometro</b></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row" style="width:500px;margin-left:3%;margin-top:100px;">
            <div class="col s12 m7 l6">
                <div class="card" style="width:300px;height:440px">
                    <div class="card-image">
                        <img src="{% static 'css/img/boton.png' %}" style="width:270px;margin-left:17px;">
                    </div>
                    <div class="card-content">
                        <p>Este es el cuarto ejercicio, un boton "chistoso" en Javascript.</p>
                    </div>
                    <div class="card-action">
                        <a href="{% url 'blog_app:boton' %}" style="color:black;"><b>Ir a boton</b></a>
                    </div>
                </div>
            </div>
        </div>


        <div class="row" style="width:500px;margin-left:37%;margin-top:-800px;">
            <div class="col s12 m7">
                <div class="card" style="width:300px;">
                    <div class="card-image">
                        <img src="{% static 'css/img/loadbarra.png' %}" style="width:280px;height:290px;margin-left:10px;">
                    </div>
                    <div class="card-content">
                        <p>Este es el quinto ejercicio, una bara de carga en Javascript.</p>
                    </div>
                    <div class="card-action">
                        <a href="{% url 'blog_app:loading' %}" style="color:black;"><b>Ir a barra de carga</b></a>
                    </div>
                </div>
            </div>
        </div>

        <footer class="page-footer teal">
            <div class="container">
                <div class="row">
                    <div class="col l6 s12">
                        <h5 class="black-text">Page Footer</h5>
                        <p class="black-text text-lighten-4">No sabia que poner aca, pero me parecio que este footer quedaba bien, asi que ocupe un poco de espacio escribiendo una explicacion de por que tiene este contenido. Obviamente, podria tener algo util.</p>

                    </div>
                    <div class="col l3 s12">
                        <h5 class="black-text">Ejemplo</h5>
                        <p class="black-text text-lighten-4">Esto es un ejemplo de algo que podria ser util.</p>
                        <ul>
                            <a type="button" id="btngirar" class="btn-large waves-effect waves-light teal lighten-1">Boton</a>
                        </ul>
                    </div>

                </div>
            </div>

            <div class="footer-copyright">
                <div class="container" style="color:black;">
                    Agradecimientos a <a class="white-text text-lighten-3" href="http://materializecss.com">Materialize</a>, que hizo esto posible.
                </div>
            </div>
        </footer>
    </body>
</html>

blog/templates/comentarios.html
{% for mensaje in mensajes %}
    <div class="container">
        <div class="row">
            <h5><b>{{mensaje.autor}}</b></h5>
            <p>{{mensaje.mensaje}}</p>
        </div>
    </div>
{% endfor %}

blog/templates/post.html
{% block css %}

{% endblock %}

{% block content %}

{% load staticfiles %}
<head>
    <title>Post</title>
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
</head>

<a class='dropdown-button btn' data-activates='dropdown1' style="width:115px;color:black;">Ir a</a>
    <ul id='dropdown1' class='dropdown-content'>
        <li><a href="{% url 'blog_app:blog' %}">MainSite</a></li>
        <li><a href="{% url 'blog_app:cont' %}">Contacto</a></li>
        <li><a href="{% url 'blog_app:curric' %}">Curriculum</a></li>
        <li><a href="{% url 'blog_app:eje' %}">Ejercicios</a></li>
    </ul>

<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <h2 class="section-heading">{{post.titulo}}</h2>
                <h5 class="section-heading">Posted by {{post.autor}}</h5>
                <h5 class="section-heading">{{post.fecha}}</h5>
                <p>{{post.contenido}} </p>
                <h3>Comentarios:</h3>
            </div>
        </div>
    </div>
</article>

<body>



        <script type="text/javascript" src="{% static 'js/jquery-2.1.4.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>

<div id="mensajes">
    {% include "comentarios.html" %}
</div>



    <form id="contactForm">
        {% csrf_token %}
        <div class="container">
            <ul class="collection with-header">
                <li class="collection-header"><h4>Deja tu comentario</h4></li>

                <li class="collection-item"><div><b>Nombre:</b>
                    <div class="row">
                        <div class="input-field col s6">
                            <input id="nombre" type="text" style="height:13px;" class="validate">
                        </div>
                    </div>
                <li class="collection-item"><div><b>Mail:</b>
        <div class="row">
            <div class="input-field col s6">
                <input id="mail" type="text" style="height:13px;" class="validate">
            </div>
        </div>
            <li class="collection-item"><div><b>Comentario:</b> 
                <div class="row">
                    <div class="input-field col s6">
                        <input id="comentario" type="text" style="height:13px;" class="validate">
                        <input value="Send" id="send" type="button" style="color:black;"></input>
                    </div>
                </div>
    </form>



<script>

    $("#send").click(function comentario(){
        var data={
            csrfmiddlewaretoken: '{{ csrf_token }}',
            autor:$("#nombre").val(),
            mensaje:$("#comentario").val(),
            mail:$("#mail").val(),
            id:'{{post.id}}',
        }
        $.ajax({
            method: "POST",
            url: "{% url 'blog_app:mensaje' %}",
            data: data,
            success:function(result){
		$("#mensajes").html(result);
                	$("#nombre").val("");
		$("#mail").val("");
                	$("#comentario").val("");
            },
            error: function(e){
                console.log(e.responseText);
            },
        });

    });
</script>

</body>

{% endblock %}

{% block scripts %}

{% endblock %}